name: woudy_customers_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.8.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  go_router: ^16.2.0
  flutter_screenutil: ^5.9.3
  oktoast: ^3.4.0
  cached_network_image: ^3.4.1
  # intl: ^0.20.1
  logger: ^2.5.0
  dartz: ^0.10.1
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  hive: ^2.2.3
  get_it: ^8.0.2
  hive_flutter: ^1.1.0
  dio: ^5.7.0
  google_fonts: ^6.2.1
  mask_text_input_formatter: ^2.9.0
  country_flags: ^3.0.0
  flutter_svg: ^2.0.16
  flutter_spinkit: ^5.2.1
  formz: ^0.8.0
  data_connection_checker_tv: ^0.3.5-nullsafety
  form_builder_validators: ^11.0.0
  flutter_form_builder: ^10.0.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  firebase_core: ^4.1.0
  firebase_crashlytics: ^5.0.0
  google_sign_in: ^7.1.1
  mapbox_maps_flutter: ^2.10.0
  flutter_dotenv: ^6.0.0
  geolocator: ^14.0.2
  shimmer_animation: ^2.2.2
  sign_in_with_apple: ^7.0.1
  hydrated_bloc: ^10.1.1
  onesignal_flutter: ^5.3.4
  uuid: ^4.5.1
  dio_cache_interceptor: ^4.0.5
  http_cache_hive_store: ^5.0.1


dependency_overrides:
  # json_serializable: ^6.7.1  # ou une autre version compatible
  build_runner: ^2.4.10      # ou une autre version compatible
  # build: ^2.4.0              
  intl: '0.19.0'

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0
  # build_runner: ^2.7.0
  freezed: ^3.0.0-0.0.dev
  json_serializable: ^6.9.5


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon_app.png"
  remove_alpha_ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/icons/maps/
    - assets/fonts/
    - assets/icons/tabs-icons/
    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
          
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
          
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-LightItalic.ttf
          weight: 300
          style: italic
          
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        # Votre dossier Poppins-Italic.ttf semble être la version 400 italique
        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
          weight: 400
          style: italic 
          
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
          
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
          
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
          
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
          
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins/Poppins-BlackItalic.ttf
          weight: 900
          style: italic

    - family: Omnes
      fonts:
        - asset: assets/fonts/Omnes/Omnes Thin.ttf
          weight: 100
        - asset: assets/fonts/Omnes/Omnes Thin Italic.ttf
          weight: 100
          style: italic
                    
        - asset: assets/fonts/Omnes/Omnes ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Omnes/Omnes ExtraLight Italic.ttf
          weight: 200
          style: italic
          
        - asset: assets/fonts/Omnes/Omnes Light.ttf
          weight: 300
        - asset: assets/fonts/Omnes/Omnes Light Italic.ttf
          weight: 300
          style: italic
          
        - asset: assets/fonts/Omnes/Omnes Regular.ttf
          weight: 400
        # Votre dossier Omnes-Italic.ttf semble être la version 400 italique
        - asset: assets/fonts/Omnes/Omnes Italic.ttf
          weight: 400
          style: italic
          
        - asset: assets/fonts/Omnes/Omnes Medium.ttf
          weight: 500
        - asset: assets/fonts/Omnes/Omnes Medium Italic.ttf
          weight: 500
          style: italic
          
        - asset: assets/fonts/Omnes/Omnes SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Omnes/Omnes SemiBold Italic.ttf
          weight: 600
          style: italic
          
        - asset: assets/fonts/Omnes/Omnes Bold.ttf
          weight: 700
        - asset: assets/fonts/Omnes/Omnes Bold Italic.ttf
          weight: 700
          style: italic
          
        - asset: assets/fonts/Omnes/Omnes Black.ttf
          weight: 900
        - asset: assets/fonts/Omnes/Omnes Black Italic.ttf
          weight: 900
          style: italic
    
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto/Roboto-ThinItalic.ttf
          weight: 100
          style: italic

        - asset: assets/fonts/Roboto/Roboto-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Roboto/Roboto-ExtraLightItalic.ttf
          weight: 200
          style: italic
          
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-LightItalic.ttf
          weight: 300
          style: italic
          
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Italic.ttf
          weight: 400
          style: italic
          
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
          
        - asset: assets/fonts/Roboto/Roboto-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Roboto/Roboto-SemiBoldItalic.ttf
          weight: 600
          style: italic
          
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
          
        - asset: assets/fonts/Roboto/Roboto-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Roboto/Roboto-ExtraBoldItalic.ttf
          weight: 800
          style: italic
          
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto/Roboto-BlackItalic.ttf
          weight: 900
          style: italic


    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter/Inter-ThinItalic.ttf
          weight: 100
          style: italic
          
        - asset: assets/fonts/Inter/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter/Inter-ExtraLightItalic.ttf
          weight: 200
          style: italic
          
        - asset: assets/fonts/Inter/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter/Inter-LightItalic.ttf
          weight: 300
          style: italic
          
        - asset: assets/fonts/Inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter/Inter-Italic.ttf
          weight: 400
          style: italic
          
        - asset: assets/fonts/Inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/Inter-MediumItalic.ttf
          weight: 500
          style: italic
          
        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/Inter-SemiBoldItalic.ttf
          weight: 600
          style: italic
          
        - asset: assets/fonts/Inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter/Inter-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Inter/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter/Inter-Black.ttf
          weight: 900
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
